[package]
name = "von-worker"
version.workspace = true
edition.workspace = true
license.workspace = true

[dev-dependencies]
dotenvy = { workspace = true }

[dependencies]
von-api = { workspace = true }
von-error = { workspace = true }
von-log = { workspace = true }
von-migrate = { workspace = true }
von-types = { workspace = true }

chrono = { workspace = true }
dotenvy = { workspace = true }
hex = { workspace = true }
hmac = { workspace = true }
redis = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
